version: '3.8'

services:
  api:
    image: queryarchive-api:latest
    build:
      context: ./QueryArchive.Api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=(localdb)\\mssqllocaldb;Database=QueryArchive;Trusted_Connection=True;MultipleActiveResultSets=true

  web:
    image: queryarchive-web:latest
    build:
      context: ./QueryArchive.Web
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ApiSettings__BaseUrl=http://api:80
    depends_on:
      - api
